package com.example.clubprojava.model.Enum;

public enum Job {
    COACH,
    ASSISTANT_COACH,
    GOALKEEPER_COACH,
    FITNESS_COACH,
    PHYSIOTHERAPIST,
    TEAM_DOCTOR,
    ANALYST,
    SCOUT,
    SPORTING_DIRECTOR,
    PRESIDENT,
    VICE_PRESIDENT,
    PRESS_OFFICER,
    KIT_MANAGER,
    TEAM_MANAGER,
    NUTRITIONIST
}
